import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "../Provider";


export const metadata: Metadata = {
  title: "Chess-game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body >
          {children}
        </body>
      </Providers>
    </html>
  );
}
